apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: sameer1703/nodeapp:4.0
        name: nodeapp
        env:
        - name: APP_NAME
          value: "KUBERNETES-101"
        - name: FIRST_NAME
          valueFrom:
            configMapKeyRef:
              name: sample-cm
              key: first
        - name: LAST_NAME
          valueFrom:
            configMapKeyRef:
              name: sample-cm
              key: last
        ports:
        - containerPort: 3000