# Use an official Node.js runtime as a parent image
FROM node:22-alpine

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY package*.json ./

# Install any needed packages specified in package.json
RUN npm install

# Make port 3000 available to the world outside this container
COPY . .

# env variables
ENV PORT 3000

EXPOSE 3000

# Run app.js when the container launches
CMD [ "node", "index.js", "start" ]
